"""initial migration

Revision ID: b74ea1262042
Revises: 
Create Date: 2026-03-02 20:53:40.126876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74ea1262042'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.Column('CategoryName', sa.String(length=255), nullable=False),
    sa.Column('Subcategory', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('CategoryID')
    )
    op.create_index(op.f('ix_categories_CategoryID'), 'categories', ['CategoryID'], unique=False)
    op.create_table('customers',
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('CustomerName', sa.String(length=255), nullable=False),
    sa.Column('CustomerEmail', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('Password_Hash', sa.String(length=255), nullable=False),
    sa.Column('Address', sa.String(length=500), nullable=True),
    sa.Column('Creat_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('CustomerID')
    )
    op.create_index(op.f('ix_customers_CustomerEmail'), 'customers', ['CustomerEmail'], unique=True)
    op.create_index(op.f('ix_customers_CustomerID'), 'customers', ['CustomerID'], unique=False)
    op.create_table('paymentmethods',
    sa.Column('PaymentMethodID', sa.Integer(), nullable=False),
    sa.Column('ModeName', sa.String(length=100), nullable=False),
    sa.Column('PayDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('PaymentMethodID')
    )
    op.create_index(op.f('ix_paymentmethods_PaymentMethodID'), 'paymentmethods', ['PaymentMethodID'], unique=False)
    op.create_table('orders',
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=True),
    sa.Column('PaymentMethodID', sa.Integer(), nullable=True),
    sa.Column('OrderDate', sa.Date(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['customers.CustomerID'], ),
    sa.ForeignKeyConstraint(['PaymentMethodID'], ['paymentmethods.PaymentMethodID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_index(op.f('ix_orders_OrderID'), 'orders', ['OrderID'], unique=False)
    op.create_table('products',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('Category', sa.Integer(), nullable=True),
    sa.Column('ProductName', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.String(length=1000), nullable=True),
    sa.Column('Image_url', sa.String(length=500), nullable=True),
    sa.Column('UnitPrice', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['Category'], ['categories.CategoryID'], ),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_index(op.f('ix_products_ProductID'), 'products', ['ProductID'], unique=False)
    op.create_table('orderitems',
    sa.Column('OrderItemID', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=True),
    sa.Column('ProductID', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('PriceAtPurchase', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Profit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Discount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['OrderID'], ['orders.OrderID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['products.ProductID'], ),
    sa.PrimaryKeyConstraint('OrderItemID')
    )
    op.create_index(op.f('ix_orderitems_OrderItemID'), 'orderitems', ['OrderItemID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderitems_OrderItemID'), table_name='orderitems')
    op.drop_table('orderitems')
    op.drop_index(op.f('ix_products_ProductID'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_OrderID'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_paymentmethods_PaymentMethodID'), table_name='paymentmethods')
    op.drop_table('paymentmethods')
    op.drop_index(op.f('ix_customers_CustomerID'), table_name='customers')
    op.drop_index(op.f('ix_customers_CustomerEmail'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_categories_CategoryID'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
